project:
  type: website

website:
  title: "`meta` Variables for Precise Includes"
  navbar: 
    left:
      - href: index.qmd
        text: "Home"
      - href: new-york.qmd
      - href: pa.qmd
      


format:
  html:
    theme: yeti
    css: styles.css
    toc: true



